name: t_shirt_calculator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gherkin: 2.0.0
  glob: ^2.1.3
  flutter_driver:
    sdk: flutter 
  test: 1.25.15

flutter:
  uses-material-design: true
